options:
  swift-release:
    default: distro
    type: str
    description: Swift PPA to configure (trunk, milestone, distro)
  block-device:
    default: sdb
    type: str
    description: Block device to format, mount and use for storing swift objects (WARNING!)
